---
title: "JoJo Graph Fun"
author: "JoJo Rystrøm"
date: "11/5/2021"
output: html_document
---
```{r}
pacman::p_load(tidyverse, tidygraph, fastnet, lubridate, reldist, zoo, ggraph, network, ggraph, netrankr, extrafont, seriation, NetSwan, fastnet)
```

# Helper functions
```{r}
create_graph <- function(dat) {
  vertices <- tibble(name=sort(unique(c(dat$from, dat$to))))
  edges <- dat
  
  tbl_graph(vertices, edges, directed = F)
}

calc_entropy <- function(graph_obj) {
  metric.degree.entropy(from.igraph(graph_obj))
}

get_edge_identifier <- function(g, id_col=date) {
  g %>% 
    activate(edges) %>% 
    as_tibble() %>% 
    distinct(!!sym(id_col)) %>% 
    pull()
}

entropy_per_date <- function(graph) {
  entropy <- calc_entropy(graph)
  date <- get_edge_date(graph)
  tibble(date=date, entropy=entropy)
}

create_pair_key <- function(a, b) {
  apply(cbind(a, b), 1, function(x) paste(sort(x), collapse=" "))
}
add_pairs <- function(graph) {
   graph %>%
    activate(edges) %>%
    as_tibble() %>%
    mutate(pair_key = create_pair_key(to, from))
}

calc_friendship_strength <- function(graph) {
   graph %>% 
    add_pairs %>% 
    group_by(pair_key, date) %>% 
    summarise(pair_weight = sum(weight))
}


calc_gini_per_day <- function(graph) {
  graph %>% 
    calc_friendship_strength %>% 
    summarise(gini_coef = gini(pair_weight), date = first(date))
}

# exponentially weighted moving average (adapted from https://stackoverflow.com/a/42774577/10524429)
ewma.filter <- function (x, ratio=0.9) {
  c(stats::filter(x * ratio, 1 - ratio, "recursive", init = x[1]))
}

# gets only last (for summarise)
ewma.filter.last <- function (x, ratio=0.9) {
  ewma_vec <- ewma.filter(x, ratio)
  ewma_vec[length(ewma_vec)]
}

add_streaks <- function(friendship_df, window_size = 4) {
  friendship_df %>%
    mutate(
      previous_streak = rollsum(
        is_friend,
        k = window_size,
        fill = NA,
        align = "right"
      ),
      next_streak = rollsum(
        is_friend,
        k = window_size,
        fill = NA,
        align = "left"
      ),
    )
}

add_connection_logic <- function(friendship_df, window_size=7) {
  friendship_df %>% 
    add_streaks %>% 
      mutate(
    previos_average = next_streak / previous_streak,
    new_connection = (friend_ratio >= 2) & next_streak > 1, 
    lost_connection = (previous_streak == 0) & !new_connection
  )  
}


entropy_in_interval <- function(df, intervalos) {
  df %>% 
    filter(date %within% intervalos) %>% 
    pull(num_new_friends) %>% 
    ts %>% 
    pracma::approx_entropy()
}

get_period <- function(graph, period="period") {
  graph %>% 
    activate(edges) %>% 
    as_tibble %>% 
    distinct(!!sym(period)) %>% 
    pull
}

calc_weekly_pagerank <- function(graph) {
  pr <- page.rank(week_graphs[[1]])$vector
  tibble(id = names(pr), pagerank = pr, week = get_edge_identifier(graph, id_col="week"))
}


create_friendship_funk <- function(pair_df, date_col = "date") {
  pair_df %>% 
  dplyr::group_by(pair_key, !!sym(date_col)) %>% 
  summarise(friendship = sum(weight)) %>% 
  mutate(date = as.Date(!!sym(date_col))) %>% 
  group_by(pair_key) %>% 
  mutate(ewma_friendship = ewma.filter(friendship, ratio=0.95), 
         log_ewma_friend = log(ewma_friendship)) %>% 
  ungroup() %>% 
  mutate(is_friend = log_ewma_friend > 0.2)
}

get_clusters <- function(x, num_clusters=2) {
  as.factor(kmeans(x, centers=num_clusters)$cluster)
}

create_friendship_funk <- function(pair_df, date_col = "date") {
  pair_df %>% 
  dplyr::group_by(pair_key, !!sym(date_col)) %>% 
  summarise(friendship = sum(weight)) %>% 
  mutate(date = as.Date(!!sym(date_col))) %>% 
  group_by(pair_key) %>% 
  mutate(ewma_friendship = ewma.filter(friendship, ratio=0.95), 
         log_ewma_friend = log(ewma_friendship)) %>% 
  ungroup() %>% 
  mutate(is_friend = log_ewma_friend > 0.2)
}

get_participants <- function(g) {
  g %>% 
    activate(nodes) %>% 
    as_tibble %>% 
    mutate(id = row_number())
}

# Calculates local, weighted transitivy and returns in a dataframe
calc_local_transitivity <- function(g) {
  tibble(trans = transitivity(g, type="weighted")) %>% 
    mutate(id = row_number(), 
           week = get_period(g, period="week"))
}

```


# Loading data
```{r}
rawdat <- read_csv("tidy_data.csv")
dropout_dat <- read_csv("dropout_dat.csv")
```

```{r}

## CHANGE UNIT HERE
unit="day"

first_sem <- interval(ymd("2019-09-01"), ymd("2020-01-14"))
second_sem <- interval(ymd("2020-02-03"), ymd("2020-03-13"))
first_lockdown <- interval(ymd("2020-03-13"), ymd("2020-06-08"))
summerbreak <- interval(ymd("2020-06-08"), ymd("2020-08-31"))
third_sem <- interval(ymd("2020-08-31"), ymd("2020-12-31"))

dat <- rawdat %>%
  mutate(
    timestamp = lubridate::as_datetime(timestamp / 1000),
    date = round_date(timestamp, unit = unit),
    from = as.character(from),
    to = as.character(to)
  ) %>%
  filter(from != to) %>%
  #mutate(pair_key = create_pair_key(from, to)) %>%
  mutate(
    period = case_when(
      date %within% first_sem ~ "first_sem",
      date %within% second_sem ~ "second_sem",
      date %within% first_lockdown ~ "lockdown",
      date %within% summerbreak ~ "summer",
      date %within% third_sem ~ "third_sem",
    )
  )



week_dat <- dat %>% 
  ungroup() %>% 
  drop_na() %>% 
  mutate(week = round_date(timestamp, unit = "week")) %>% 
  group_by(to, from, week) %>% 
  summarise(weight = sum(weight)) 

```

### Let's fckin roll!
```{r}
week_graphs <- week_dat %>%
  ungroup() %>% 
  group_split(week) %>% 
  map(create_graph)


pagerank_df <- week_graphs %>% 
  map_dfr(calc_weekly_pagerank)


msg_df <- week_dat %>%
  group_by(from, week) %>%
  summarise(num_msgs = sum(weight)) %>%
  ungroup() %>%
  mutate(vacation = !((week %within% first_sem) |
                        (week %within% second_sem) |
                        (week %within% first_lockdown) |  (week %within% third_sem)
  )) %>% 
  mutate(lockdown = week %within% first_lockdown | week %within% third_sem)

```

```{r}
week_friends <- week_graphs %>% 
  map_dfr(add_pairs) %>% 
  create_friendship_funk(date_col = "week") %>%
  group_by(pair_key) %>% 
  mutate(friendship_strength = rollsum(friendship, 4, fill = NA, align = "right") / 4, 
         new_con = friendship > (2*friendship_strength), 
         timecol = as.factor(as.integer(as.factor(week))))
  
participants <- week_graphs[[2]] %>% 
  activate(nodes) %>% 
  as_tibble %>% 
  mutate(id = row_number())


num_friends_df <- tibble()
for (i in 1:max(participants$id)) {
  pattern <- paste0("\\b", i, "\\b")
  temp_df <- week_friends %>%
    filter(str_detect(pair_key, pattern)) %>%
    group_by(date) %>%
    summarise(num_friends = sum(is_friend), 
              new_cons = sum(new_con)) %>%
    ungroup() %>%
    mutate(id = participants$name[[i]])
  
  num_friends_df <- num_friends_df %>% 
    bind_rows(temp_df)
}

num_friends_df %>% 
  ggplot(aes(x=new_cons)) +
  geom_histogram()

```

```{r}

model_data <- pagerank_df %>% 
  unite(join_id, id, week, remove=FALSE) %>% 
  left_join(unite(msg_df, join_id, from, week)) %>% 
  left_join(unite(num_friends_df, join_id, id, date)) %>% 
  group_by(week) %>% 
  fill(vacation, lockdown) %>% 
  ungroup() %>% 
  mutate(num_msgs = replace_na(num_msgs, 0)) %>% 
  drop_na() 

model_data %>% 
  summarise(across(everything(), ~sum(is.na(.x))))
```


### Adding transitivity / centrality
```{r}
trans_df <- week_graphs %>% 
  map_dfr(calc_local_transitivity) %>% 
  left_join(get_participants(week_graphs[[1]]), by="id") %>% 
  select(-id) %>% 
  rename(id=name) %>% 
  unite(join_id, id, week)

model_data %>% 
  left_join(trans_df) %>%  
  select(-join_id) %>% 
  write_csv("brms_model_data.csv")
```

```{r}
new_con_df %>% 
  ggplot(aes(x=new_cons)) + 
  geom_histogram()

model_data <- read_csv("brms_model_data.csv")

model_data %>% 
  ggplot(aes(x = new_cons)) +
  geom_histogram()
```

# Lost connections
```{r}

lost_dat <- week_friends %>% 
  mutate(lost_con = friendship < 0.5 * friendship_strength, 
         lockdown = week %within% first_lockdown | week %within% third_sem,
         timecol = as.factor(as.integer(as.factor(week)))) %>% 
  select(pair_key, timecol, friendship, friendship_strength = friendship_strength, lost_con, lockdown, week)  


week_cols <- tibble(week = unique(lost_dat$week)) %>% 
  arrange(week) %>% 
  mutate(timecol = as.factor(as.integer(as.factor(week))))

full_dat <- lost_dat %>% 
  expand(pair_key, timecol) %>% 
  left_join(week_cols)




full_dat %>% 
  left_join(select(week_friends, pair_key, timecol, friendship), by = c("pair_key", "timecol")) %>% 
  mutate(friendship = replace_na(friendship, 0),
         friendship_strength = rollsum(friendship, 4, fill = NA, align = "right") / 4,
         lost_con = (friendship < 0.5 * friendship_strength) & friendship_strength > 0.001, 
         lockdown = week %within% first_lockdown | week %within% third_sem) %>% 
  drop_na() %>%  
  filter(week < as.Date("2021-01-01")) %>% 
  write_csv("disaster_dat.csv")

```

