---
title: "JoJo Graph Fun"
author: "JoJo Rystrøm"
date: "11/5/2021"
output: html_document
---
```{r}
pacman::p_load(tidyverse, tidygraph, fastnet, lubridate, reldist, zoo)
```

# Helper functions
```{r}
create_graph <- function(dat) {
  vertices <- tibble(name=sort(unique(c(dat$from, dat$to))))
  edges <- dat
  
  tbl_graph(vertices, edges, directed = F)
}

calc_entropy <- function(graph_obj) {
  metric.degree.entropy(from.igraph(graph_obj))
}

get_edge_identifier <- function(g, id_col=date) {
  g %>% 
    activate(edges) %>% 
    as_tibble() %>% 
    distinct(!!sym(id_col)) %>% 
    pull()
}

entropy_per_date <- function(graph) {
  entropy <- calc_entropy(graph)
  date <- get_edge_date(graph)
  tibble(date=date, entropy=entropy)
}

create_pair_key <- function(a, b) {
  apply(cbind(a, b), 1, function(x) paste(sort(x), collapse=" "))
}
add_pairs <- function(graph) {
   graph %>%
    activate(edges) %>%
    as_tibble() %>%
    mutate(pair_key = create_pair_key(to, from))
}

calc_friendship_strength <- function(graph) {
   graph %>% 
    add_pairs %>% 
    group_by(pair_key, date) %>% 
    summarise(pair_weight = sum(weight))
}


calc_gini_per_day <- function(graph) {
  graph %>% 
    calc_friendship_strength %>% 
    summarise(gini_coef = gini(pair_weight), date = first(date))
}

# exponentially weighted moving average (adapted from https://stackoverflow.com/a/42774577/10524429)
ewma.filter <- function (x, ratio=0.9) {
  c(stats::filter(x * ratio, 1 - ratio, "recursive", init = x[1]))
}

# gets only last (for summarise)
ewma.filter.last <- function (x, ratio=0.9) {
  ewma_vec <- ewma.filter(x, ratio)
  ewma_vec[length(ewma_vec)]
}

add_streaks <- function(friendship_df, window_size = 4) {
  friendship_df %>%
    mutate(
      previous_streak = rollsum(
        is_friend,
        k = window_size,
        fill = NA,
        align = "right"
      ),
      next_streak = rollsum(
        is_friend,
        k = window_size,
        fill = NA,
        align = "left"
      ),
    )
}

add_connection_logic <- function(friendship_df, window_size=7) {
  friendship_df %>% 
    add_streaks %>% 
      mutate(
    friend_ratio = next_streak / previous_streak,
    new_connection = (friend_ratio >= 3) & next_streak > 1, 
    lost_connection = (previous_streak == 0) & !new_connection
  ) %>% 
    select(-c(previous_streak, next_streak, friend_ratio))
}


entropy_in_interval <- function(df, intervalos) {
  df %>% 
    filter(date %within% intervalos) %>% 
    pull(num_new_friends) %>% 
    ts %>% 
    pracma::approx_entropy()
}

get_period <- function(graph) {
  graph %>% 
    activate(edges) %>% 
    as_tibble %>% 
    distinct(period) %>% 
    pull
}

calc_weekly_pagerank <- function(graph) {
  pr <- page.rank(week_graphs[[1]])$vector
  tibble(id = names(pr), pagerank = pr, week = get_edge_identifier(graph, id_col="week"))
}


create_friendship_funk <- function(pair_df, date_col = "date") {
  pair_df %>% 
  dplyr::group_by(pair_key, !!sym(date_col)) %>% 
  summarise(friendship = sum(weight)) %>% 
  mutate(date = as.Date(!!sym(date_col))) %>% 
  group_by(pair_key) %>% 
  mutate(ewma_friendship = ewma.filter(friendship, ratio=0.95), 
         log_ewma_friend = log(ewma_friendship)) %>% 
  ungroup() %>% 
  mutate(is_friend = log_ewma_friend > 0.2)
}

get_clusters <- function(x, num_clusters=2) {
  as.factor(kmeans(x, centers=num_clusters)$cluster)
}

create_friendship_funk <- function(pair_df, date_col = "date") {
  pair_df %>% 
  dplyr::group_by(pair_key, !!sym(date_col)) %>% 
  summarise(friendship = sum(weight)) %>% 
  mutate(date = as.Date(!!sym(date_col))) %>% 
  group_by(pair_key) %>% 
  mutate(ewma_friendship = ewma.filter(friendship, ratio=0.95), 
         log_ewma_friend = log(ewma_friendship)) %>% 
  ungroup() %>% 
  mutate(is_friend = log_ewma_friend > 0.2)
}
```


# Loading data
```{r}
rawdat <- read_csv("tidy_data.csv")
dropout_dat <- read_csv("dropout_dat.csv")
```

```{r}
pacman::p_load(tidyverse, network, tidygraph, lubridate, ggraph, netrankr, extrafont, seriation, NetSwan, fastnet)


## CHANGE UNIT HERE
unit="day"

first_sem <- interval(ymd("2019-09-01"), ymd("2020-01-14"))
second_sem <- interval(ymd("2020-02-03"), ymd("2020-03-13"))
first_lockdown <- interval(ymd("2020-03-13"), ymd("2020-06-08"))
summerbreak <- interval(ymd("2020-06-08"), ymd("2020-08-31"))
third_sem <- interval(ymd("2020-08-31"), ymd("2020-12-31"))

dat <- rawdat %>%
  mutate(
    timestamp = lubridate::as_datetime(timestamp / 1000),
    date = round_date(timestamp, unit = unit),
    from = as.character(from),
    to = as.character(to)
  ) %>%
  filter(from != to) %>%
  #mutate(pair_key = create_pair_key(from, to)) %>%
  mutate(
    period = case_when(
      date %within% first_sem ~ "first_sem",
      date %within% second_sem ~ "second_sem",
      date %within% first_lockdown ~ "lockdown",
      date %within% summerbreak ~ "summer",
      date %within% third_sem ~ "third_sem",
    )
  )


sum_dat <- dat %>% 
  drop_na() %>% 
  group_by(to, from, period) %>% 
  summarise(weight = sum(weight)) 
sum_dat

week_dat <- dat %>% 
  ungroup() %>% 
  drop_na() %>% 
  mutate(week = round_date(timestamp, unit = "week")) %>% 
  group_by(to, from, week) %>% 
  summarise(weight = sum(weight)) 

```

## Calculating entropy
```{r}
graph_list <- dat %>% 
  group_split(date) %>% 
  map(create_graph) 

entropy_df <- graph_list %>% 
  map_dfr(entropy_per_date)


entropy_df %>% 
  mutate(date = as.Date(date)) %>% 
  ggplot(aes(x=date, y=entropy)) + 
  geom_line() + 
  geom_vline(xintercept=as.Date("2020-03-11"), colour="red") + 
  geom_smooth() + 
  theme_minimal()
```

## Calculating GINI-coefficient
```{r}
gini_df <- graph_list %>% 
  map_dfr(calc_gini_per_day)
```

### The power of friendship
```{r}
master_graph <- create_graph(dat)

pair_df <- add_pairs(master_graph)

friendship_df <- pair_df %>% 
  dplyr::group_by(pair_key, date) %>% 
  summarise(friendship = sum(weight)) %>% 
  mutate(date = as.Date(date)) %>% 
  group_by(pair_key) %>% 
  mutate(ewma_friendship = ewma.filter(friendship, ratio=0.95), 
         log_ewma_friend = log(ewma_friendship)) %>% 
  ungroup() %>% 
  mutate(is_friend = log_ewma_friend > 0.2) 



con_df <- friendship_df %>% 
  group_by(pair_key) %>% 
  add_connection_logic(window_size = 7)


new_cons <- con_df %>% 
  group_by(date) %>% 
  summarise(num_new_friends = sum(new_connection, na.rm=T))

new_cons %>% 
  ggplot(aes(x=date, y=num_new_friends)) + 
  geom_line() +
  geom_vline(xintercept=as.Date("2020-03-11"), colour="red")



friendship_df %>% 
  filter(date < ymd("2021-01-01")) %>% 
  group_by(date) %>% 
  summarise(friend_score = mean(ewma_friendship)) %>% 
  ggplot(aes(date, friend_score)) + 
  geom_line()

length(test_sum)


new_cons %>% 
  filter(date %within% third_sem)

entropy_in_interval(new_cons, intro_interval)
entropy_in_interval(new_cons, second_sem)
entropy_in_interval(new_cons, first_lockdown)
entropy_in_interval(new_cons, third_sem)
```

```{r}
transitivity(master_graph, type="weighted")
```



```{r}
con_df %>% 
  ggplot(aes(x = log_ewma_friend)) + 
  geom_density()
```

```{r}
gini_df %>% 
period_graphs <- sum_dat %>%
  ungroup() %>% 
  group_split(period) %>% 
  map(create_graph)

period_graphs

test_period <- period_graphs[[1]]

test_period
trans_first <- test_period %>% 
  transitivity(type = "weighted")

trans_stuff <- period_graphs %>% 
  map(~transitivity(.x, type="barrat"))

trans_stuff %>% 
  map_dbl(gini)


trans_stuff %>% 
  map_dbl(mean)

trans_stuff %>% 
  map_dbl(sd)


?t.test

period_graphs %>% 
  map_chr(get_period)
period_graphs
trans_stuff %>% mutate(date = as.Date(date)) %>% 
  ggplot(aes(x=date, y=gini_coef)) + 
  geom_line() + 
  geom_vline(xintercept=as.Date("2020-03-11"), colour="red") + 
  geom_smooth() + 
  theme_minimal()
```

### Check period stuff
```{r}

```

### Pseudo-model
```{r}
alist(num_friends <- num_messages_ewma > threshold)
alist(num_friends ~ PageRank + vacation + num_messages + lockdown + (1|ID))

# Can be done per week

```


### Let's fckin roll!
```{r}
week_graphs <- week_dat %>%
  ungroup() %>% 
  group_split(week) %>% 
  map(create_graph)


pagerank_df <- week_graphs %>% 
  map_dfr(calc_weekly_pagerank)


msg_df <- week_dat %>%
  group_by(from, week) %>%
  summarise(num_msgs = sum(weight)) %>%
  ungroup() %>%
  mutate(vacation = !((week %within% first_sem) |
                        (week %within% second_sem) |
                        (week %within% first_lockdown) |  (week %within% third_sem)
  )) %>% 
  mutate(lockdown = week %within% first_lockdown | week %within% third_sem)

msg_df
```

```{r}
week_friends <- week_graphs %>% 
  map_dfr(add_pairs) %>% 
  create_friendship_funk(date_col = "week")

participants <- week_graphs[[2]] %>% 
  activate(nodes) %>% 
  as_tibble %>% 
  mutate(id = row_number())


num_friends_df <- tibble()
for (i in 1:max(participants$id)) {
  pattern <- paste0("\\b", i, "\\b")
  temp_df <- week_friends %>%
    filter(str_detect(pair_key, pattern)) %>%
    group_by(date) %>%
    summarise(num_friends = sum(is_friend)) %>%
    ungroup() %>%
    mutate(id = participants$name[[i]])
  
  num_friends_df <- num_friends_df %>% 
    bind_rows(temp_df)
}
```

```{r}

model_data <- pagerank_df %>% 
  unite(join_id, id, week, remove=FALSE) %>% 
  left_join(unite(msg_df, join_id, from, week)) %>% 
  left_join(unite(num_friends_df, join_id, id, date)) %>% 
  group_by(week) %>% 
  fill(vacation, lockdown) %>% 
  ungroup() %>% 
  mutate(num_msgs = replace_na(num_msgs, 0)) %>% 
  drop_na() %>% 
  select(-join_id)
  

write_csv(model_data, "brms_model_data.csv")

model_data %>% 
  summarise(across(everything(), ~sum(is.na(.x))))
```

```{r}
msg_summary <- week_dat %>% 
  group_by(from, to, week) %>% 
  summarise(num_msgs = sum(weight), 
            log_msgs = log(num_msgs)) 

plot_data <- msg_summary %>% 
  filter(from=="235")



plot_data %>% 
  ggplot(aes(x = log_msgs, colour = from)) + 
  geom_density() + 
  geom_vline(xintercept = mean(plot_data$log_msgs))




msg_summary <- msg_summary %>% 
  group_by(from) %>% 
  mutate(cluster = get_clusters(log_msgs)) %>% 
  ungroup() 

msg_summary %>% 
  ggplot(aes(x = log_msgs, fill = cluster)) + 
  geom_histogram() + 
  facet_wrap(~from)


```

```{r}
new_con_df <- msg_summary %>% 
  group_by(from) %>% 
  mutate(mean_1 = mean(log_msgs[cluster == "1"]),
         mean_2 = mean(log_msgs[cluster == "2"]), 
         ) %>% 
  mutate(is_friend = as.numeric(cluster) - 1, 
         is_friend = if_else(mean_1 < mean_2, as.logical(is_friend), !is_friend)) %>% 
 add_connection_logic(window_size = 4) %>% 
 group_by(id=from, week) %>% 
 summarise(new_cons = sum(new_connection)) 

new_con_df %>% 
  group_by(week) %>% 
  summarise(mean_new_con = mean(new_cons)) %>% 
  ggplot(aes(x = week, y=mean_new_con)) + 
  geom_line()

model_data %>% 
  unite(join_id, id, week, remove=FALSE) %>% 
  left_join(unite(new_con_df, join_id, id, week)) %>%  
  mutate(new_cons = replace_na(new_cons, 0)) %>% 
  select(-join_id) %>% 
  write_csv("brms_model_data.csv")
```

Funk som man kunne tilføje
- temporale dynamikker i netværket (e.g. avg. response time)
  - avg. response time
- interaktioner?     