---
title: "Soccult anal"
author: "JoJo Rystrøm"
date: "16/5/2021"
output: html_document
---

## Loading libries
```{r}
pacman::p_load(tidyverse, brms, job)
```

```{r}
rawdat <- read_csv("brms_model_data.csv")
```

```{r}
rethinking::dens(rbeta(1000, 1, 1))

?rgamma
```


```{r}
dat <- rawdat %>% 
  mutate(timecol = as.integer(as.factor(week)))

dat %>% 
  filter(new_cons > 0 ) %>% 
  summarise(mean(log(new_cons)), sd(log(new_cons)))

m0_f <- bf(new_cons ~ 0 + timecol + lockdown*pagerank*trans + (1 | id))


m1_f <- bf(new_cons ~ 0 + timecol + lockdown + lockdown:pagerank + lockdown:trans + (1 | id))

get_prior(m1_f, data=dat, family=zero_inflated_negbinomial())

m0_priors <- c(
  prior(normal(0, 0.1), class=b), 
  prior(normal(0, 0.1), class=sd), 
  prior(gamma(0.01, 0.01), class=shape),
  prior(beta(1, 1), class=zi)
)
 
m0_prior_model <- brm(
  m1_f,
  dat,
  family=zero_inflated_negbinomial(),
  prior=m0_priors,
  sample_prior = "only",
  cores = 2,
  chains = 2,
  backend = "cmdstanr", 
  control = list(adapt_delta = 0.99, max_treedepth=20))

pp_check(m0_prior_model, nsamples=100)

job::job(brm_result = {
  fit = brm(
  m1_f,
  dat,
  family=zero_inflated_negbinomial(),
  prior=m0_priors,
  sample_prior = T,
  cores = 2,
  chains = 2,
  backend = "cmdstanr", 
  control = list(adapt_delta = 0.99, max_treedepth=20))
  pos_check =  pp_check(m0_testy, nsamples = 100)
})

summary(m0_testy)
hypothesis(m0_testy, "lockdownTRUE < lockdownFALSE")
hypothesis(m0_testy, "abs(lockdownTRUE:pagerank) > 0")
```

```{r}
summary(brm_result$fit)
brm_result$pos_check

hypothesis(brm_result$fit, "abs(lockdownTRUE:trans - lockdownFALSE:trans) > 0")

hypothesis(brm_result$fit, "abs(lockdownTRUE:pagerank - lockdownFALSE:pagerank) > 0")

hypothesis(brm_result$fit, "timecol<0")

```
## Posterior update checks :)) 
```{r}
posterior <- posterior_samples(brm_result$fit)
posterior


prior_posterior_update <- function(posterior, effect_col="b_lockdownTRUE") {
ggplot(posterior) +
  theme_classic() +
  geom_density(aes(prior_b), fill="red", alpha=0.3) +
  geom_density(aes(!!sym(effect_col)), fill="blue", alpha=0.5) + 
  theme_minimal() + 
  labs(title = paste("posterior update of", effect_col))
}

cols_of_interest <- c("b_lockdownTRUE","b_lockdownTRUE:pagerank", "b_lockdownTRUE:trans", "b_lockdownFALSE:trans", "b_lockdownFALSE:pagerank") 


for (col in cols_of_interest) {
  print(prior_posterior_update(posterior, col))
}
```



```{r}
dat %>% 
  ggplot(aes(x=new_cons)) + 
  geom_histogram()

dat %>% 
  ggplot(aes(x=week, y=log(new_cons))) + 
  geom_point() + 
  geom_smooth()
```
