```{r}
pacman::p_load(tidyverse, network, tidygraph, lubridate, ggraph, netrankr, extrafont, seriation)
font_import()
```


```{r}
df2 <- df %>% 
  mutate(timestamp = lubridate::as_datetime(timestamp/1000))
df2 <- df2 %>% filter(timestamp > as.Date("2020-03-01") & timestamp < as.Date("2020-04-01"))
```


```{r}
vertices <- tibble(name=unique(c(df2$from, df2$to)))
edges <- df2 %>% select(-X1)
```

```{r}
graph <- tbl_graph(vertices, edges)
```

```{r}
graph <- graph %>%  
  activate(nodes) %>% 
  mutate(degreein = centrality_degree(weights=NULL, mode="in", loops=FALSE, normalized=FALSE),
         rwalk = centrality_random_walk()) %>% 
  arrange(desc(degreein))
```

```{r}
df3 <- df2 %>% 
  mutate(tofrom = paste0(to, from)) %>% 
  group_by(to, from) %>% 
  summarise(weight = n())
```

```{r fig.height=5, fig.width=6}
df3 %>% 
  as_tbl_graph() %>% 
  activate(nodes) %>% 
  mutate(degreein = centrality_degree(weights=NULL, mode="in", loops=FALSE, normalized=FALSE),
         rwalk = centrality_random_walk(),
         pagerank = centrality_pagerank(),
         cluster = tidygraph::node_rank_quadratic(),
         community = as.factor(group_leading_eigen())) %>% 
  arrange(desc(degreein)) %>% 
   ggraph(layout ="gem") +
    geom_edge_link(aes(alpha=weight)) +
    geom_node_point(aes(size=pagerank)) +
  labs(title="Users connected by message amount", 
       subtitle="Between 1st of March and April 2020. The lockdown happened\non the 11th of March.",
       size="Pagerank",
       edge_alpha="Messages") +
  ggraph::theme_graph() +
  theme(text=element_text(family="Roboto"),
        plot.title=element_text(family="Roboto",
                                margin=margin(0,0,5,0)),
        plot.subtitle=element_text(family="Roboto",
                                   margin=margin(0)),
        legend.position="right",
        legend.direction="vertical")

```

```{r fig.width=6, fig.height=6}
df3 %>% 
  as_tbl_graph() %>% 
  activate(nodes) %>% 
  mutate(degreein = centrality_degree(weights=NULL, mode="in", loops=FALSE, normalized=FALSE),
         rwalk = centrality_random_walk(),
         pagerank = centrality_pagerank(),
         cluster = tidygraph::node_rank_quadratic(),
         community = as.factor(group_leading_eigen())) %>% 
  arrange(desc(degreein)) %>% 
   ggraph(layout ="gem") +
    geom_edge_link(aes(alpha=weight)) +
    geom_node_point(aes(size=pagerank, color=community)) +
  labs(title="Users connected by message amount", 
       subtitle="Between 1st of March and April 2020. The lockdown happened\non the 11th of March.",
       size="Pagerank",
       edge_alpha="Messages") +
  ggraph::theme_graph() +
  theme(text=element_text(family="Roboto"),
        plot.title=element_text(family="Roboto",
                                margin=margin(0,0,5,0)),
        plot.subtitle=element_text(family="Roboto",
                                   margin=margin(0)),
        legend.position="bottom",
        legend.direction="vertical")
```

```{r}
graph <- df3 %>% 
  as_tbl_graph(directed=FALSE) %>% 
  activate(nodes) %>% 
  mutate(degreein = centrality_degree(weights=NULL, mode="in", loops=FALSE, normalized=FALSE),
         rwalk = centrality_random_walk(),
         pagerank = centrality_pagerank(),
         cluster = tidygraph::node_rank_quadratic(),
         community = as.factor(group_edge_betweenness()))

igraph::cluster_edge_betweenness(graph) %>% plot(graph, vertex.label=NA)

```

```{r}



```

